name: amber_test_app
secret_key_base: ox7cTo_408i4WZkKZ_5OZZtB5plqJYhD4rxrz2hriA4
port: 4000
port_reuse: true
process_count: 16
ssl_key_file: some key file
ssl_cert_file: some cert file
host: 0.0.0.0
redis_url: "redis://localhost:6379"
session: {
  key: "myapp.session",
  store: "encrypted_cookie",
  expires: 10
}
secrets:  {
  description: "Store your test secrets credentials and settings here.",
  database: "mysql://root@localhost:3306/amber_test_app_test"
}
