version: '2'
services:
  spec:
    build: .
    command: 'bash -c "cd /app/user && crystal spec"'
    working_dir: /app/user
    tmpfs: /app/testing
    environment:
      AMBER_ENV: test 
      AMBER_ENV_PATH: ./spec/support/config
