version: '2'
services:
  spec:
    build: .
    command: 'bash -c "cd /app/user && crystal spec -D run_build_tests"'
    working_dir: /app/user
    environment:
      REDIS_URL: 'redis://redis:6379'
      AMBER_ENV: test
    depends_on:
      - redis

  redis:
    image: redis:3.2-alpine
    command: redis-server
