on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install shards
        run: shards install

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - name: Run tests
        run: crystal spec
