on:
  push:
jobs:
  amber-spec:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Update & install dependencies
        run: apt update && apt install -y libpq-dev libsqlite3-dev libreadline-dev

      - name: Download source
        uses: actions/checkout@v3

      - name: Install shards
        run: shards install

      - name: Run main tests
        run: bin/amber_spec
        env:
          DATABASE_URL: "postgres://postgres:password@postgres:5432/test_app"
          REDIS_URL: "redis://redis:6379"
          AMBER_ENV: test
