on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install shards
        run: shards install

      - name: Install redis
        run: apt-get install redis
      
      - name: Verify Redis is running
        run: redis-cli ping

      - name: Run tests
        run: bin/amber_spec
